# Generated by Django 3.1 on 2020-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='continent',
            field=models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South America')], max_length=20),
        ),
    ]
