# Generated by Django 3.1 on 2020-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_team_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('club', 'club'), ('nation', 'nation'), ('world', 'club')], max_length=20),
        ),
    ]
