# Generated by Django 3.1 on 2020-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200826_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='continent',
            field=models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South America'), ('WW', 'Worldwide')], max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('club', 'club'), ('nation', 'nation'), ('world', 'world')], max_length=20),
        ),
    ]
